// Bulk Chinese comment → English translation for all target JS files
// Only translates // and /* */ comments, never string literals or code
import { readFileSync, writeFileSync } from 'node:fs';

const TRANSLATIONS = {
  'background.js': [
    // Already done in first 2 edits — skip those sections
    // Row around line 96-98: no more Chinese there
    // line ~117: already done
    // Around line 141:
    ['  // ---- 多周期共振分支 ----', '  // ---- multi-period resonance branch ----'],
    ['  // 取数据（个股 + 沪深300 并行）', '  // fetch data (stock + HS300 in parallel)'],
    ['  // 沪深300 指标计算', '  // HS300 indicator calculation'],
    ['  // 命中缓存', '  // cache hit'],
    ['  // 计算指标', '  // compute indicators'],
    ["  // ---- 自我回测（仅 single 模式，数据 ≥36 根） ----", '  // ---- self-backtest (single mode only, >= 36 bars) ----'],
    ['          // 先查缓存（仅缓存 LLM 判断，actual return 实时计算）', '          // check cache first (only cache LLM judgment, actual return computed live)'],
    ['            console.log(`[backtest] cutoff=${cutoff} 命中缓存`);', '            console.log(`[backtest] cutoff=${cutoff} cache hit`);'],
    ['            console.log(`[backtest] cutoff=${cutoff} 调 LLM...`);', '            console.log(`[backtest] cutoff=${cutoff} calling LLM...`);'],
    ['          // 计算实际涨跌（不缓存，随价格实时变化）', '          // compute actual return (not cached, changes with live price)'],
    ['          console.warn(`[backtest] cutoff=${cutoff} 失败，跳过：`, err.message);', '          console.warn(`[backtest] cutoff=${cutoff} failed, skipped:`, err.message);'],
    ['            extraContext.backtestBlock = buildSelfCalibrationBlock(backtestResults);', '            extraContext.backtestBlock = buildSelfCalibrationBlock(backtestResults);'],
    ['        console.log(`[backtest] 生成校准段，${backtestResults.length} 个时点`);', '        console.log(`[backtest] generated calibration block, ${backtestResults.length} time points`);'],
    ['      console.warn(\'[backtest] 回测流程失败，跳过：\', err.message);', "      console.warn('[backtest] backtest flow failed, skipped:', err.message);"],
    ["    // 多 Agent 辩论路径", "    // multi-agent debate path"],
    ["    // 渲染：Judge 主输出 > 三段拼接退路", "    // render: Judge main output > three-agent fallback"],
    ["    // 月度用量统计:累加所有成功 Agent（含 Judge）", "    // monthly usage stats: accumulate all successful agents (incl. Judge)"],
    ["  // 单次分析路径", "  // single analysis path"],
    ["  // 尝试获取行业 alpha（通过 Native Messaging 查询 SQLite）", "  // attempt to fetch sector alpha (via Native Messaging querying SQLite)"],
    ["      // Native host 不可用时静默降级", "      // silent degrade when Native host unavailable"],
    ["  // Kronos 信号注入（默认 ON — hold-out 验证通过，参见 docs/p3-kronos-confirm.md）", "  // Kronos signal injection (default ON — hold-out validation passed, see docs/p3-kronos-confirm.md)"],
    ["      } catch (_) { /* 降级 */ }", "      } catch (_) { /* degrade */ }"],
    ["  // 反转因子已撤出（24tp 池翻负 -19.2%，参见 docs/p3-signal-gating.md）", "  // Reversal factor withdrawn (24tp pool turned negative -19.2%, see docs/p3-signal-gating.md)"],
    ["  // LSTM 信号注入开关（默认 OFF — 训练数据存在时间窗泄漏，参见 docs/p1-lstm-leak-check.md）", "  // LSTM signal injection switch (default OFF — training data has time-window leakage, see docs/p1-lstm-leak-check.md)"],
    ["        if (ulevel === 'high') {", "        if (ulevel === 'high') {\n            console.log(`[analyze] MC Dropout high uncertainty for ${code}, skipping LSTM signal`);"],
    ["            console.log(`[analyze] MC Dropout high uncertainty for ${code}, 跳过 LSTM 信号`);", ""],
    ["      // Native host 不可用或数据未预计算时静默降级", "      // silent degrade when Native host unavailable or data not pre-computed"],
    ["  // 仅 Anthropic provider 启用 tool_use", "  // enable tool_use only for Anthropic provider"],
    ["  // 流式进度 + 工具调用跟踪", "  // streaming progress + tool call tracking"],
    ["        // 从后往前找同名且未填充的，避免同名混淆", "        // search from back for same name and unfilled, to avoid same-name confusion"],
    ["      } catch (_) { /* tab 可能已关闭 */ }", "      } catch (_) { /* tab may have been closed */ }"],
    ["  // 流式期间用 alarm 保持 SW 唤醒", "  // keep SW awake with alarm during streaming"],
    ["    // 无论成功/失败，清理 alarm + 通知 content", "    // whether success or failure, clean up alarm + notify content"],
    ["  // 调试日志（仅当开关开启）", "  // debug log (only when switch enabled)"],
    ["// 结构化输出提取 + 跨级别一致性校验", "// structured output extraction + cross-level consistency check"],
    ["    // TODO: structured key 维度（仅 market/code/period）少于 analysis key（7 维度），\n    // 切换 style 时新分析会覆盖旧 structured 数据。\n    // 若不同风格输出的 structured 质量差异大，需将 style 加入 key。", "    // TODO: structured key dimensions (only market/code/period) are fewer than analysis key (7 dimensions),\n    // switching style causes new analysis to overwrite old structured data.\n    // If structured output quality varies significantly across styles, add style to the key."],
    ["  // 历史记录 ID", "  // history record ID"],
    ["  // 写缓存", "  // write cache"],
    ["  // 辩论 checkpoint 清理：正式缓存已写入，不再需要续跑数据", "  // debate checkpoint cleanup: formal cache written, no longer need resume data"],
    ["  // 写入分析历史（不含 conversationHistory，后续由 content.js 补充）", "  // write to analysis history (without conversationHistory, to be supplemented by content.js later)"],
    ["// ---- 多轮对话 ----", "// ---- multi-turn conversation ----"],
    ["// ---- 缓存 key ----", "// ---- cache key ----"],
    ["// ---- 时间 bucket ----", "// ---- time bucket ----"],
    ["// ---- 东财 K 线 ----", "// ---- Eastmoney K-lines ----"],
    ["// ---- 沪深300 K 线 ----", "// ---- HS300 K-lines ----"],
    ["  // 大盘数据获取失败不阻塞主流程", "  // index data fetch failure does not block main flow"],
    ["// ---- 月度用量统计 ----", "// ---- monthly usage statistics ----"],
    ["// ---- 多周期共振 ----", "// ---- multi-period resonance ----"],
    ["  // 三周期并发抓取 + 沪深300 月线", "  // three-period concurrent fetch + HS300 monthly"],
    ["  // 各自计算 MA + MACD", "  // compute MA + MACD for each"],
    ["  // 沪深300 月线数据", "  // HS300 monthly data"],
    ["  // 桶取日线最新日期（最细精度）", "  // bucket by daily latest date (finest granularity)"],
    ["  // multi 模式暂不缓存（prompt 体积大，缓存价值低）", "  // multi mode not cached for now (prompt is large, low cache value)"],
    ["    maxTokens: DEFAULT_MAX_TOKENS * 2, // 多周期输出需要更多 token", "    maxTokens: DEFAULT_MAX_TOKENS * 2, // multi-period output needs more tokens"],
    ["  // 历史记录 ID", "  // history record ID"],
    ["  // 写入分析历史", "  // write to analysis history"],
    ["// ---- 设置 ----", "// ---- settings ----"],
    ["  // 先跑迁移（幂等）", "  // run migration first (idempotent)"],
    ["  // 模型选择优先级：\n  // 1. 用户手动填写的 model:${provider}（非空）\n  // 2. analysisDepth 映射（仅 Anthropic）：standard → claude-sonnet-4-6, deep → claude-opus-4-7\n  // 3. provider 默认模型", "  // model selection priority:\n  // 1. user manually entered model:${provider} (non-empty)\n  // 2. analysisDepth mapping (Anthropic only): standard → claude-sonnet-4-6, deep → claude-opus-4-7\n  // 3. provider default model"],
    ["// ---- 分析历史 ----", "// ---- analysis history ----"],
    ["  // 去重：同一 code + template + timestamp（秒级）视为重复", "  // dedup: same code + template + timestamp (second-level) treated as duplicate"],
    ["  // 容量管理", "  // capacity management"],
    ["  // trimHistory 已处理条数上限，这里只做体积检查", "  // trimHistory already handles count limit, here only check size"],
    ["  // 更新时间戳", "  // update timestamp"],
    ["  // 估算占用", "  // estimate usage"],
    ["    // 导出单条", "    // export single"],
    ["    // 导出全部", "    // export all"],
    ["// ---- Native Messaging 自动同步到 Node 端 ----", "// ---- Native Messaging auto-sync to Node side ----"],
    ["// 不同步的敏感 key 前缀", "// sensitive key prefixes not to sync"],
    ["// 防抖：同一 key 的变更累积，500ms 后批量发送", "// debounce: accumulate changes for same key, batch-send after 500ms"],
    ["    // Native host 未安装或启动失败，静默忽略\n    // 数据仍在 chrome.storage.local 中，下次成功同步时会补上", "    // Native host not installed or startup failed, silently ignore\n    // data remains in chrome.storage.local, will sync on next successful attempt"],
    ["// 监听 storage 变化（content.js / popup.js 写入时触发自动同步）", "// listen for storage changes (trigger auto-sync when content.js / popup.js writes)"],
  ],
  'content.js': [
    ["// content script: 注入 Shadow DOM 侧边面板,管理内容侧缓存,监听 URL 变化自动触发分析", "// content script: inject Shadow DOM side panel, manage content-side cache, monitor URL changes to auto-trigger analysis"],
    ["          <span class=\"thinking-status\" data-role=\"thinkingStatus\">AI 正在分析...</span>", "          <span class=\"thinking-status\" data-role=\"thinkingStatus\">AI analyzing...</span>"],
    ["  let lastAnalyzedCode = ''; // 用于 URL 变化检测", "  let lastAnalyzedCode = ''; // for URL change detection"],
    ["  let currentAnalysisId = null; // 当前分析的历史记录 ID", "  let currentAnalysisId = null; // history record ID of current analysis"],
    ["// ---------- 思考流 UI ----------", "// ---------- thinking stream UI ----------"],
    ["    thinkingStatusEl.textContent = 'AI 正在分析...';", "    thinkingStatusEl.textContent = 'AI analyzing...';"],
    ["  // 监听后台推进的 STREAM_PROGRESS", "  // listen for STREAM_PROGRESS from background"],
    ["        // 更新对应的工具调用行", "        // update the corresponding tool call line"],
    ["// ---------- 从页面提取当前价格 ----------", "// ---------- extract current price from page --------"],
    ["    // 尝试从页面标题解析", "    // try parsing from page title"],
    ["// ---------- 从分析文本提取位置百分位 ----------", "// ---------- extract position percentile from analysis text --------"],
    ["    // 匹配 \"第 XX 百分位\" 或 \"XX.XX% 的位置\" 等模式", "    // match patterns like \"XX percentile\" or \"at XX% position\""],
    ["// ---------- 内容侧缓存 ----------", "// ---------- content-side cache ----------"],
    ["    // 30 天过期", "    // 30 day expiry"],
    ["// ---------- 从页面抓取事件 ----------", "// ---------- scrape events from page ----------"],
    ["// ---------- 解析股票代码 ----------", "// ---------- parse stock code ----------"],
    ["function parseCodeFromUrl(url) {", "function parseCodeFromUrl(url) {\n    // Eastmoney URL actual format: quote.eastmoney.com/sh600519.html (no slash separator)"],
    ["    // 东财 URL 实际格式: quote.eastmoney.com/sh600519.html（无斜杠分隔）", ""],
    ["// ---------- 主分析流程 ----------", "// ---------- main analysis flow ----------"],
    ["    setBody('<div class=\"loading\">正在加载…</div>');", "    setBody('<div class=\"loading\">Loading…</div>');"],
    ["        setBody('<div class=\"error\">service worker 无响应，可能扩展未加载</div>');", "        setBody('<div class=\"error\">service worker has no response, extension may not be loaded</div>');"],
    ["// ---------- 仪表盘 JSON 解析 ----------", "// ---------- dashboard JSON parsing ----------"],
    ["      signalBadgeEl.textContent = '⚠️ 本次未生成结构化数据，仅显示文本分析';", "      signalBadgeEl.textContent = '⚠️ No structured data generated this round, text analysis only';"],
    ["      return `<div class=\"analysis\">${renderMarkdown(md)}</div>`;", "      return `<div class=\"analysis\">${renderMarkdown(md)}</div>`;\n    }\n\n    // Card foldable rendering"],
    ["    }\n\n    return sections.map((sec) => {", "    return sections.map((sec) => {"],
    ["          <div class=\"card-body ${bodyClass}\">", "          <div class=\"card-body ${bodyClass}\">\n            ${renderMarkdown(sec.body)}"],
    ["            ${renderMarkdown(sec.body)}", ""],
    ["// Markdown 按 ## / ### 分段", "// split Markdown by ## / ### headings"],
    ["          sections.push({ title: currentTitle || '概述', body: bodyText });", "          sections.push({ title: currentTitle || 'Overview', body: bodyText });"],
    ["    if (currentTitle || bodyText) {\n      sections.push({ title: currentTitle || '概述', body: bodyText });", "    if (currentTitle || bodyText) {\n      sections.push({ title: currentTitle || 'Overview', body: bodyText });"],
    ["  // 卡片折叠点击", "  // card fold toggle click"],
    ["// ---------- Markdown 渲染 ----------", "// ---------- Markdown rendering ----------"],
    ["    // 跳过单个 ``` 标记", "    // skip bare ``` markers"],
    ["        const level = Math.min(h[1].length + 2, 5); // 卡片内从 h3 开始", "        const level = Math.min(h[1].length + 2, 5); // start from h3 inside cards"],
    ["    // 编号列表", "    // numbered list"],
    ["// ---------- 多轮对话 ----------", "// ---------- multi-turn conversation ----------"],
    ["    // 跳过首次 prompt（太长，不渲染）", "    // skip first prompt (too long, don't render)"],
    ["          <div class=\"chat-bubble\">📊 首次分析 prompt（已提交，长度 ${msg.content.length} 字符）</div>", "          <div class=\"chat-bubble\">📊 First analysis prompt (submitted, ${msg.content.length} chars)</div>"],
    ["  // 20 条以上 warning", "  // warning for 20+ messages"],
    ["    if (conversationHistory.length >= 20) {\n      chatWarningEl.style.display = 'block';\n      chatWarningEl.textContent = `⚠️ 对话已达 ${conversationHistory.length} 条，token 消耗较大。建议清空对话后重新开始。`;", "    if (conversationHistory.length >= 20) {\n      chatWarningEl.style.display = 'block';\n      chatWarningEl.textContent = `⚠️ Conversation reached ${conversationHistory.length} messages, high token usage. Suggest clearing and starting fresh.`;"],
    ["    // 渲染 user 消息", "    // render user message"],
    ["    // 添加加载占位", "    // add loading placeholder"],
    ["      const resp = await chrome.runtime.sendMessage({", "      const resp = await chrome.runtime.sendMessage({"],
    ["    // 移除加载占位", "    // remove loading placeholder"],
    ["  // 保存对话到历史", "  // save conversation to history"],
    ["    // 保留前两条（首次 prompt + 首次分析结果）", "    // keep first two messages (initial prompt + initial analysis)"],
    ["// ---------- URL 变化监听 ----------", "// ---------- URL change monitoring ----------"],
    ["// Monkey-patch pushState / replaceState", "// monkey-patch pushState / replaceState"],
    ["// ---------- 自动触发 ----------", "// ---------- auto-trigger ----------"],
    ["  // 页面加载完成后自动分析", "  // auto-analyze after page loads"],
  ],
  'popup.js': [
    ["// popup 设置页 + 预设模式 + 成本面板 + 分析历史 + 调试面板", "// popup settings page + preset modes + cost panel + analysis history + debug panel"],
    ["// provider 配置", "// provider configuration"],
    ["// 预设定义", "// preset definitions"],
    ["// ---------- Tab 切换 ----------", "// ---------- Tab switching ----------"],
    ["// ---------- Provider UI ----------", "// ---------- Provider UI ----------"],
    ["// ---------- 成本面板 ----------", "// ---------- cost panel ----------"],
    ["    $('costValue').textContent = '暂无调用记录';", "    $('costValue').textContent = 'No call records yet';"],
    ["// ---------- 预设模式 ----------", "// ---------- preset modes ----------"],
    ["// 把预设值写入表单", "// write preset values to form"],
    ["// 动态显示/隐藏选项", "// dynamically show/hide options"],
    ["  // 详细设置折叠", "  // detail settings collapse"],
    ["    toggleLabel.textContent = '收起详细设置';", "    toggleLabel.textContent = 'Collapse detail settings';"],
    ["    toggleLabel.textContent = '展开详细设置';", "    toggleLabel.textContent = 'Expand detail settings';"],
    ["  // Provider 相关", "  // Provider-related"],
    ["    : 'DeepSeek 固定使用 deepseek-chat';", "    : 'DeepSeek always uses deepseek-chat';"],
    ["  // 辩论模式相关", "  // debate mode-related"],
    ["  // Thinking：仅 Opus 可用，standard 时灰化", "  // Thinking: only available for Opus, grayed out on standard"],
    ["      $('rowThinking').querySelector('.hint').textContent = '仅 Opus（深度模式）可用，当前为标准模式';", "      $('rowThinking').querySelector('.hint').textContent = 'Only Opus (deep mode) available, currently on standard mode';"],
    ["      $('rowThinking').querySelector('.hint').textContent = '仅在 Anthropic Opus 模型下生效。';", "      $('rowThinking').querySelector('.hint').textContent = 'Only effective with Anthropic Opus model.';"],
    ["  // DeepSeek 模型锁定", "  // DeepSeek model lock"],
    ["// 更新摘要行", "// update summary row"],
    ["  $('presetSummary').textContent = '当前：' + p.label + ' | ' + providerLabel + ' ' + p.model + ' | 估算成本：' + p.estCost;", "  $('presetSummary').textContent = 'Current: ' + p.label + ' | ' + providerLabel + ' ' + p.model + ' | Est. cost: ' + p.estCost;"],
    ["// 预设按钮点击", "// preset button click"],
    ["      // 填入当前保存的 API key", "      // fill current saved API key"],
    ["        $('apiKey').placeholder = key ? '已保存 (' + key.length + ' 字符)' : PROVIDER_DEFS[PRESETS[preset].provider].apiKeyPattern;", "        $('apiKey').placeholder = key ? 'Saved (' + key.length + ' chars)' : PROVIDER_DEFS[PRESETS[preset].provider].apiKeyPattern;"],
    ["// 展开/收起详细设置", "// expand/collapse detail settings"],
    ["  $('settingsToggleLabel').textContent = open ? '收起详细设置' : '展开详细设置';", "  $('settingsToggleLabel').textContent = open ? 'Collapse detail settings' : 'Expand detail settings';"],
    ["// Provider 变化时刷新 UI", "// refresh UI when provider changes"],
    ["    $('apiKey').placeholder = items['apiKey:' + newProvider] ? '已保存 (' + items['apiKey:' + newProvider].length + ' 字符)' : PROVIDER_DEFS[newProvider].apiKeyPattern;", "    $('apiKey').placeholder = items['apiKey:' + newProvider] ? 'Saved (' + items['apiKey:' + newProvider].length + ' chars)' : PROVIDER_DEFS[newProvider].apiKeyPattern;"],
    ["// debateMode 变化时刷新", "// refresh when debateMode changes"],
    ["// analysisDepth 变化时刷新 thinking 灰化", "// refresh thinking gray-out when analysisDepth changes"],
    ["// ---------- 设置加载 ----------", "// ---------- settings loading ----------"],
    ["  $('apiKey').placeholder = currentApiKey ? '已保存 (' + currentApiKey.length + ' 字符)' : PROVIDER_DEFS[providerId].apiKeyPattern;", "  $('apiKey').placeholder = currentApiKey ? 'Saved (' + currentApiKey.length + ' chars)' : PROVIDER_DEFS[providerId].apiKeyPattern;"],
    ["// ---------- 保存 ----------", "// ---------- save ----------"],
    ["  setStatus('已保存');", "  setStatus('Saved');"],
    ["  setStatus('Key 已清除');", "  setStatus('Key cleared');"],
    ["// ---------- 快速导航 ----------", "// ---------- quick navigation ----------"],
    ["  if (!code) { hint.textContent = '请输入股票代码'; hint.style.color = '#e74c3c'; return; }", "  if (!code) { hint.textContent = 'Please enter stock code'; hint.style.color = '#e74c3c'; return; }"],
    ["  if (!url) { hint.textContent = '无法识别代码 \"' + code + '\"，沪市 6 开头，深市 0/3 开头'; hint.style.color = '#e74c3c'; return; }", "  if (!url) { hint.textContent = 'Cannot recognize code \"' + code + '\", SH market starts with 6, SZ starts with 0/3'; hint.style.color = '#e74c3c'; return; }"],
    ["// ---------- 历史 Tab ----------", "// ---------- History Tab ----------"],
    ["      $('historyList').innerHTML = '<div class=\"history-empty\">加载失败</div>'; return;", "      $('historyList').innerHTML = '<div class=\"history-empty\">Load failed</div>'; return;"],
    ["    if (historyListCache.length === 0) {\n      $('historyList').innerHTML = '<div class=\"history-empty\">暂无保存的分析记录</div>';", "    if (historyListCache.length === 0) {\n      $('historyList').innerHTML = '<div class=\"history-empty\">No saved analysis records</div>';"],
    ["    } else { renderHistoryCards(); $('historyGlobalActions').style.display = 'flex'; }\n  } catch (_) { $('historyList').innerHTML = '<div class=\"history-empty\">加载失败</div>'; }", "    } else { renderHistoryCards(); $('historyGlobalActions').style.display = 'flex'; }\n  } catch (_) { $('historyList').innerHTML = '<div class=\"history-empty\">Load failed</div>'; }"],
    ["      + '<span class=\"hi-badge ' + (hasConv ? 'hasconv' : '') + '\">' + (hasConv ? '有追问' : '仅分析') + '</span>'", "      + '<span class=\"hi-badge ' + (hasConv ? 'hasconv' : '') + '\">' + (hasConv ? 'With followup' : 'Analysis only') + '</span>'"],
    ["      + '<button class=\"h-btn h-btn-export\" data-action=\"export\" data-idx=\"' + idx + '\">📥 导出</button>'", "      + '<button class=\"h-btn h-btn-export\" data-action=\"export\" data-idx=\"' + idx + '\">📥 Export</button>'"],
    ["      + '<button class=\"h-btn h-btn-del\" data-action=\"delete\" data-idx=\"' + idx + '\">🗑 删除</button></div></div>';", "      + '<button class=\"h-btn h-btn-del\" data-action=\"delete\" data-idx=\"' + idx + '\">🗑 Delete</button></div></div>';"],
    ["  if (!conv || conv.length <= 2) return '';\n  const msgs = conv.slice(2);\n  if (msgs.length === 0) return '';\n  let html = '<div class=\"conv-section\"><h4>追问记录</h4>';", "  if (!conv || conv.length <= 2) return '';\n  const msgs = conv.slice(2);\n  if (msgs.length === 0) return '';\n  let html = '<div class=\"conv-section\"><h4>Follow-up records</h4>';"],
    ["  if (!confirm('删除 ' + (entry.name || '?') + '(' + (entry.code || '?') + ') 的分析记录?')) return;", "  if (!confirm('Delete analysis record for ' + (entry.name || '?') + '(' + (entry.code || '?') + ')?')) return;"],
    ["  if (!confirm('确认清空全部 ' + historyListCache.length + ' 条分析记录? 此操作不可撤销。')) return;", "  if (!confirm('Confirm clearing all ' + historyListCache.length + ' analysis records? This is irreversible.')) return;"],
    ["// ---------- 简易 Markdown 渲染 ----------", "// ---------- simple Markdown rendering ----------"],
    ["// ---------- 调试 Tab ----------", "// ---------- Debug Tab ----------"],
    ["  $('debugToolCalls').innerHTML = '<div style=\"padding:8px 10px;font-size:12px;color:#888;\">无工具调用</div>';", "  $('debugToolCalls').innerHTML = '<div style=\"padding:8px 10px;font-size:12px;color:#888;\">No tool calls</div>';"],
    ["// ---------- 工具 ----------", "// ---------- utilities ----------"],
    ["// ---------- 启动 ----------", "// ---------- startup ----------"],
    ["  // 调试面板折叠/复制", "  // debug panel collapse/copy"],
    ["      if (el) { navigator.clipboard.writeText(el.textContent || ''); e.target.textContent = '已复制!'; setTimeout(() => { e.target.textContent = '复制'; }, 1500); }", "      if (el) { navigator.clipboard.writeText(el.textContent || ''); e.target.textContent = 'Copied!'; setTimeout(() => { e.target.textContent = 'Copy'; }, 1500); }"],
    ["      contentEl.innerHTML = '<div style=\"font-size:11px;color:#999;margin-top:6px;\">暂无结构化数据缓存</div>';", "      contentEl.innerHTML = '<div style=\"font-size:11px;color:#999;margin-top:6px;\">No structured data cache</div>';"],
  ],
  'lib/build-prompt.js': [
    ["// prompt 拼装，两个入口：\n//   buildPromptByTemplate() → single 模式用（新 4 维度模板）\n//   buildPrompt()          → debate 模式用（旧 4 风格，保留兼容）", "// prompt assembly, two entry points:\n//   buildPromptByTemplate() → for single mode (new 4-dimension templates)\n//   buildPrompt()          → for debate mode (legacy 4 styles, kept for compat)"],
    ["// resonance 函数动态导入，避免 service worker 加载 Node 原生模块 (better-sqlite3)", "// resonance functions dynamically imported to avoid service worker loading Node native modules (better-sqlite3)"],
    ["// ---- 大盘对照段（百分比计算，不再输出完整 K 线表格） ----", "// ---- index comparison section (percentage calculation, no longer outputs full K-line table) ----"],
    ["// ---- 新模板系统入口（single 模式用） ----", "// ---- new template system entry (for single mode) ----"],
    ["  // 数据窗口（第 4 条硬约束用）", "  // data window (for 4th hard constraint)"],
    ["  // 第 6 条硬约束：仅月线/周线启用区分已收盘 K 线", "  // 6th hard constraint: only monthly/weekly enable distinguishing closed bars"],
    ["  // 数据健康检查", "  // data health check"],
    ["  // 预计算技术指标", "  // pre-compute technical indicators"],
    ["  // 结构化信号识别", "  // structured signal identification"],
    ["  // 取模板任务文本", "  // get template task text"],
    ["  // 自我回测校准段", "  // self-backtest calibration block"],
    ["  // 大盘对照（百分比格式）", "  // index comparison (percentage format)"],
    ["  // HS300 行业内 Alpha（相对行业基准的超额收益）", "  // HS300 intra-industry Alpha (excess return vs industry benchmark)"],
    ["  // LSTM 日线预测信号", "  // LSTM daily prediction signal"],
    ["  // 多时间窗口归一化回报", "  // multi-time-window normalized returns"],
    ["  // 多周期共振", "  // multi-period resonance"],
    ["// ---- 旧风格入口（debate 模式保留） ----", "// ---- legacy style entry (kept for debate mode) ----"],
  ],
  'lib/self-backtest.js': [
    ["// 自我回测 decision log\n// 让 AI 在分析当前股票时看到自己在该股票历史时点的判断 + 实际涨跌 + alpha，\n// 据此校准当前置信度\n//\n// 3 个导出函数：\n//   runHistoricalAnalysis()  — 在历史 cutoff 点调 LLM 拿判断\n//   calculateActualReturn() — 纯数值计算实际涨跌 + alpha\n//   buildSelfCalibrationBlock() — 生成 markdown 校准段", "// Self-backtest decision log\n// Let AI see its own past judgments on this stock + actual returns + alpha,\n// to calibrate current confidence accordingly\n//\n// 3 exported functions:\n//   runHistoricalAnalysis()  — call LLM at historical cutoff point to get judgment\n//   calculateActualReturn() — pure numeric calculation of actual return + alpha\n//   buildSelfCalibrationBlock() — generate markdown calibration block"],
    ["// 回测固定用轻量模型（省成本）", "// backtest always uses lightweight model (cost saving)"],
    ["// ---- 判断提取 ----", "// ---- judgment extraction ----"],
    ["// 从 LLM 输出中提取方向判断和关键价位", "// extract directional judgment and key price levels from LLM output"],
    ["  // 提取关键价位（XX.XX 格式的价位，取前 3 个）", "  // extract key price levels (XX.XX format, take first 3)"],
    ["// ---- 回测判断缓存 ----", "// ---- backtest judgment cache ----"],
    ["// ---- 主函数 ----", "// ---- main functions ----"],
    ["  // 重新计算 MA/MACD（因为截断后指标需要重算）", "  // recompute MA/MACD (indicators need recalculation after truncation)"],
    ["  // 构造 prompt（不含 tool_use，不含大盘对照，省 token）", "  // construct prompt (no tool_use, no index comparison, save tokens)"],
    ["    // 不传 market → 不注入 tool_use 指令，回测不需要", "    // no market → no tool_use instruction injection, not needed for backtest"],
    ["  // 调 LLM（强制用轻量模型）", "  // call LLM (force lightweight model)"],
    ["    maxTokens: 2000, // 回测省 token，2000 够判断", "    maxTokens: 2000, // save tokens for backtest, 2000 enough for judgment"],
    ["    // 找沪深300同期最接近的 K 线", "    // find closest HS300 K-line for same period"],
    ["    lines.push('请综合上述自我校准结果，调整本次判断的置信度。');", "    lines.push('Please synthesize the above self-calibration results and adjust confidence for the current judgment.');"],
    ["    lines.push('注意：模型在历史时点的判断也可能存在偏差，以上信息仅供校准参考，不作为绝对依据。');", "    lines.push('Note: model judgments at historical time points may also have biases; the above information is for calibration reference only, not as absolute basis.');"],
    ["// 导出缓存函数供 background.js 使用", "// export cache functions for use by background.js"],
  ],
  'lib/cross-section.js': [
    ["// 横截面分析引擎 — 行业内相对排名\n// 把单股绝对预测升级为行业内相对排名", "// Cross-section analysis engine — intra-industry relative ranking\n// Upgrades single-stock absolute prediction to intra-industry relative ranking"],
    ["  // 统计", "  // statistics"],
    ["  // 标准差", "  // standard deviation"],
    ["  // 强度标签（相对于中性50分）", "  // strength tag (relative to neutral 50)"],
    ["  // 为每只股票补全行业排名信息", "  // enrich each stock with industry ranking info"],
    ["  // 按行业分组", "  // group by industry"],
    ["  // 行业排名", "  // industry ranking"],
    ["  // 轮动信号（强弱差top5对子）", "  // rotation signals (top-5 strong/weak pairs)"],
    ["  * 给单个scoreData补充cross_section字段", "  * enrich a single scoreData with cross_section field"],
  ],
  'lib/score-fusion.js': [
    ["// LLM+量化混合评分融合 v2 — 自适应regime检测\n// 根据量化因子自身强度动态选择融合权重，避免sideways/high_vol灾难性恶化", "// LLM+quant hybrid score fusion v2 — adaptive regime detection\n// Dynamically select fusion weights based on quant factor strength, avoiding catastrophic degradation in sideways/high_vol"],
    [" * 检测股票当前处于什么regime\n * 用 F2_pricePosition + F3_volatilityPct 组合替代 F1_trend 绝对值阈值", " * Detect what regime the stock is currently in\n * Use F2_pricePosition + F3_volatilityPct combo instead of F1_trend absolute threshold"],
    ["  // 极端位置 + 低波 = 真趋势（价格推到极值且波动不大）", "  // extreme position + low vol = true trend (price at extreme with low volatility)"],
    ["  // 中间位置 + 低波 = 真震荡（价格卡在区间中段）", "  // mid position + low vol = true sideways (price stuck in range middle)"],
    ["  // 高波动", "  // high volatility"],
    ["/** 自适应权重表 */", "/** adaptive weight table */"],
    [" * score → signal 映射", " * score → signal mapping"],
    [" * 融合LLM和量化评分", " * fuse LLM and quant scores"],
    ["  // 处理缺失", "  // handle missing"],
    ["  // LLM score: 0-100 → -100~100", "  // LLM score: 0-100 → -100~100"],
    ["  // 方向一致性", "  // directional agreement"],
    ["  // 自适应regime检测", "  // adaptive regime detection"],
    ["    // 旧逻辑：按agreement分配", "    // legacy logic: weight by agreement"],
  ],
  'lib/industry-map.js': [
    ["// 行业映射 — 加载data/industry-map.json，内存缓存", "// Industry mapping — loads data/industry-map.json, in-memory cache"],
  ],
  'lib/quant-factors.js': [
    ["// 量化因子计算 — 纯函数，无副作用\n// klines不够24根时返回null，不抛错", "// Quantitative factor computation — pure functions, no side effects\n// Returns null when klines < 24 bars, no throw"],
    [" * f1: 趋势强度 (-1~+1)\n * 用短中长期均线斜率综合判断", " * f1: trend strength (-1~+1)\n * Composite judgment using short/mid/long-term MA slopes"],
    ["  // 计算3条均线: MA5, MA20, MA60", "  // compute 3 MAs: MA5, MA20, MA60"],
    ["  // 短期斜率: MA5最近5根的变化率", "  // short-term slope: MA5 change rate over last 5 bars"],
    ["  // 中期斜率: MA20最近10根的变化率", "  // mid-term slope: MA20 change rate over last 10 bars"],
    ["  // 均线排列: MA5 > MA20 > MA60", "  // MA alignment: MA5 > MA20 > MA60"],
    ["  // 综合: 斜率 + 排列", "  // composite: slope + alignment"],
    [" * f2: 价格位置 (0~1)\n * 当前价在近N根K线中的百分位", " * f2: price position (0~1)\n * Current price percentile among last N bars"],
    [" * f3: 波动率百分位 (0~1)\n * 当前波动率在历史中的位置", " * f3: volatility percentile (0~1)\n * Current volatility position in history"],
    ["  // 计算每根K线的振幅", "  // compute amplitude for each bar"],
    ["  // 中值附近分数低，极端值分数高（适合趋势股定义）", "  // low score near median, high score at extremes (suits trend-following stock definition)"],
    [" * f4: 量价配合 (-1 / 0 / +1)\n * 最近3根K线的量价关系", " * f4: volume-price confirmation (-1 / 0 / +1)\n * Volume-price relationship of last 3 bars"],
    ["    const prevs = klines.slice(-6, -3); // 前3根用于比较量", "    const prevs = klines.slice(-6, -3); // previous 3 bars for volume comparison"],
    ["    // 和前三根的平均量对比", "    // compare with average volume of previous 3 bars"],
    ["    if (priceUp && volUp) confirmScore += 1;   // 放量上涨 ✓\n    else if (!priceUp && volUp) confirmScore -= 1; // 放量下跌 ✗\n    else if (priceUp && !volUp) confirmScore -= 0.5; // 缩量上涨 △\n    else confirmScore += 0.5; // 缩量下跌（可能衰竭）", "    if (priceUp && volUp) confirmScore += 1;   // rising on volume ✓\n    else if (!priceUp && volUp) confirmScore -= 1; // falling on volume ✗\n    else if (priceUp && !volUp) confirmScore -= 0.5; // rising on shrinking volume △\n    else confirmScore += 0.5; // falling on shrinking volume (possible exhaustion)"],
    [" * 综合量化评分 (-100 ~ +100)", " * Composite quant score (-100 ~ +100)"],
    ["  // 加权\n  // trend: 35%, position: 25%, volatility: 15%, volume: 25%", "  // weighting\n  // trend: 35%, position: 25%, volatility: 15%, volume: 25%"],
    ["  // confidence: 基于因子一致性", "  // confidence: based on factor agreement"],
    ["  const confidence = +(agreement * 0.8 + 0.2).toFixed(2); // floor 0.2", "  const confidence = +(agreement * 0.8 + 0.2).toFixed(2); // floor at 0.2"],
  ],
};

const BASE = 'D:\\ClaudeProjects\\eastmoney-monthly-ai';

for (const [filename, replacements] of Object.entries(TRANSLATIONS)) {
  const filePath = `${BASE}\\${filename}`;
  let content = readFileSync(filePath, 'utf-8');
  let changed = 0;
  let skipped = 0;
  for (const [oldStr, newStr] of replacements) {
    if (oldStr === newStr) continue;
    if (!content.includes(oldStr)) {
      skipped++;
      continue;
    }
    if (newStr === '') {
      // deletion
      content = content.replace(oldStr, '');
      changed++;
    } else {
      const count = (content.match(new RegExp(oldStr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length;
      content = content.replaceAll(oldStr, newStr);
      changed += count;
    }
  }
  writeFileSync(filePath, content, 'utf-8');
  console.log(`${filename}: ${changed} replacements applied, ${skipped} entries skipped (not found)`);
}
